#!/usr/bin/env bash
# hermes-agent-workflow / scripts / setup-remote-claude.sh
#
# Install the `claude-remote` shell function into the user's shell rc
# file. The function brings up a per-host tmux session running
# `claude remote-control`, which exposes the session to claude.ai and
# the Claude iOS app — letting the user drive their agent from a phone.
#
# On warm start the function tells Claude to read
# `claude-session-history.md` so the new session picks up the
# project's running narrative instead of starting cold.
#
# Idempotent: re-running replaces the previously generated block in
# place (the begin/end markers below are how we recognize it).
set -euo pipefail

# ── 0. UI helpers ────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  C_GREEN=$'\033[0;32m'; C_RED=$'\033[0;31m'; C_YELLOW=$'\033[0;33m'
  C_BOLD=$'\033[1m'; C_RESET=$'\033[0m'
else
  C_GREEN=""; C_RED=""; C_YELLOW=""; C_BOLD=""; C_RESET=""
fi
ok()    { printf '%s✓%s %s\n' "${C_GREEN}" "${C_RESET}" "$*"; }
warn()  { printf '%s!%s %s\n' "${C_YELLOW}" "${C_RESET}" "$*"; }
fail()  { printf '%s✗%s %s\n' "${C_RED}" "${C_RESET}" "$*" >&2; exit 1; }
info()  { printf '%s→%s %s\n' "${C_BOLD}" "${C_RESET}" "$*"; }

BEGIN_MARKER="# >>> hermes-agent-workflow remote-claude >>>"
END_MARKER="# <<< hermes-agent-workflow remote-claude <<<"

# ── 1. Verify prerequisites ──────────────────────────────────────────
if ! command -v tmux >/dev/null 2>&1; then
  fail "tmux not on PATH. Install: apt install tmux  |  brew install tmux"
fi
ok "tmux found ($(command -v tmux))"

if ! command -v claude >/dev/null 2>&1; then
  fail "claude (Claude Code CLI) not on PATH. Install: https://claude.com/claude-code"
fi
ok "claude found ($(command -v claude))"

# remote-control may be a newer subcommand; warn but don't abort.
if ! claude remote-control --help >/dev/null 2>&1; then
  warn "claude remote-control --help did not run cleanly — your Claude Code"
  warn "  may predate the remote-control subcommand. The function will be"
  warn "  installed anyway; upgrade Claude Code if invocation fails."
fi

# ── 2. Resolve the instance repo path ────────────────────────────────
# Preference order:
#   1. $HERMES_INSTANCE_REPO (caller-provided)
#   2. $PWD if it looks like the workflow repo (claude-session-history.md present)
#   3. interactive prompt
HISTORY_FILENAME="claude-session-history.md"
RESOLVED_REPO=""

if [[ -n "${HERMES_INSTANCE_REPO:-}" ]]; then
  RESOLVED_REPO="${HERMES_INSTANCE_REPO}"
  info "using HERMES_INSTANCE_REPO=${RESOLVED_REPO}"
elif [[ -f "${PWD}/${HISTORY_FILENAME}" ]]; then
  RESOLVED_REPO="${PWD}"
  info "detected workflow repo at PWD: ${RESOLVED_REPO}"
else
  read -r -p "  Path to your hermes-agent-workflow fork: " RESOLVED_REPO
  RESOLVED_REPO="${RESOLVED_REPO/#\~/$HOME}"
  if [[ -z "${RESOLVED_REPO}" ]]; then
    fail "no instance repo path provided"
  fi
fi

if [[ ! -f "${RESOLVED_REPO}/${HISTORY_FILENAME}" ]]; then
  warn "${RESOLVED_REPO}/${HISTORY_FILENAME} not found"
  warn "  the function will still install, but warm-start context-load will"
  warn "  no-op until that file exists."
fi
ok "instance repo: ${RESOLVED_REPO}"

# ── 3. Detect shell rc file ──────────────────────────────────────────
# We look at $SHELL (login shell from /etc/passwd) rather than $0,
# because this script runs in its own bash regardless of the user's
# interactive shell. Fall back to ~/.bashrc with a warning if $SHELL
# is something we don't recognize.
RC_FILE=""
case "${SHELL##*/}" in
  bash) RC_FILE="${HOME}/.bashrc" ;;
  zsh)  RC_FILE="${HOME}/.zshrc"  ;;
  *)
    warn "unrecognized login shell (${SHELL}); writing to ~/.bashrc anyway"
    RC_FILE="${HOME}/.bashrc"
    ;;
esac
touch "${RC_FILE}"
ok "shell rc: ${RC_FILE}"

# ── 4. Build the function block ──────────────────────────────────────
# The instance-repo path is baked in at install time as the default,
# but $HERMES_INSTANCE_REPO at runtime wins (so users can switch repos
# without re-running the installer).
read -r -d '' BLOCK <<EOF || true
${BEGIN_MARKER}
# Generated by scripts/setup-remote-claude.sh — do not edit by hand.
# Re-run the script to regenerate this block.
claude-remote() {
  local host="\${HOST_NAME:-\$(hostname -s)}"
  local sess="claude-\${host}"
  local repo="\${HERMES_INSTANCE_REPO:-${RESOLVED_REPO}}"
  local hist="\$repo/${HISTORY_FILENAME}"
  if tmux has-session -t "\$sess" 2>/dev/null; then
    return 0
  fi
  # Pre-flight: repo must exist on disk. Without this, a missing repo
  # would manifest as the generic "session died immediately" error
  # below, because the inner 'cd \$repo' fails and claude bails.
  if [ ! -d "\$repo" ]; then
    echo "claude-remote: instance repo not found at: \$repo" >&2
    echo "  Fix: set HERMES_INSTANCE_REPO=/path/to/repo, or re-run" >&2
    echo "       hermes-agent-workflow/scripts/setup-remote-claude.sh" >&2
    echo "       from your instance repo to re-bake the default." >&2
    return 1
  fi
  # We cd into the instance repo (not \$HOME) for two reasons:
  #  1. \$HOME often isn't a trusted workspace, so 'claude remote-control'
  #     bails with "Workspace not trusted" before tmux even sees output.
  #  2. The repo IS the project context the warm-start prompt is about,
  #     so cwd-sensitive tools (git, ls, grep) just work.
  # --spawn=same-dir is pinned: the alternative ('worktree') asks git
  # to materialize a fresh checkout per session, which trips the
  # git-crypt smudge filter on .env (the worktree's \$GIT_DIR has no
  # git-crypt/keys/default) and aborts session creation. same-dir
  # reuses the already-unlocked checkout. Pressing 'w' inside
  # remote-control toggles this and persists it to ~/.claude.json as
  # tengu_worktree_mode=true — passing the flag overrides that.
  tmux new-session -d -s "\$sess" -x 200 -y 50 \\
    "cd \$repo && claude remote-control --name \$sess --spawn=same-dir"
  # claude remote-control sometimes exits immediately (auth failure,
  # account doesn't have the feature, version mismatch) — that kills
  # the only window in the new session, which kills the session, which
  # tears down the tmux server, which makes the deferred send-keys
  # below print 'no server running'. Wait briefly and re-check; if the
  # session is gone, surface an actionable error and return non-zero
  # so the caller knows.
  sleep 2
  if ! tmux has-session -t "\$sess" 2>/dev/null; then
    echo "claude-remote: session '\$sess' died immediately." >&2
    echo "  Run this directly to see the error:" >&2
    echo "      claude remote-control --name \$sess" >&2
    return 1
  fi
  if [ -f "\$hist" ]; then
    (sleep 5 && tmux send-keys -t "\$sess" \\
      "Read \$hist end-to-end. That is the running project history; use it to pick up where we left off. Acknowledge briefly and tell me what is on the backlog." Enter) &
  fi
}
${END_MARKER}
EOF

# ── 5. Install or replace the block in the rc file ───────────────────
if grep -qF "${BEGIN_MARKER}" "${RC_FILE}"; then
  info "existing block found in ${RC_FILE} — replacing"
  TMP="$(mktemp)"
  awk -v begin="${BEGIN_MARKER}" -v end="${END_MARKER}" -v block="${BLOCK}" '
    BEGIN { in_block = 0; printed = 0 }
    $0 == begin { in_block = 1; print block; printed = 1; next }
    $0 == end   { in_block = 0; next }
    !in_block   { print }
    END {
      if (!printed) { print block }
    }
  ' "${RC_FILE}" > "${TMP}"
  mv "${TMP}" "${RC_FILE}"
  ok "block replaced"
else
  info "appending block to ${RC_FILE}"
  printf '\n%s\n' "${BLOCK}" >> "${RC_FILE}"
  ok "block appended"
fi

# ── 6. Hand off ──────────────────────────────────────────────────────
cat <<EOF

${C_BOLD}Next steps${C_RESET}
  Reload your shell so the function is available:
    source ${RC_FILE}
  (or open a new terminal)

  Then bring up your remote session:
    claude-remote

  That starts a tmux session named claude-\$(hostname -s) running
  Claude Code in remote-control mode. Open claude.ai (web or iOS) and
  the session will be attachable from your phone.

EOF
ok "setup-remote-claude done"
